name: fy_country_state_city
description: "Package description"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fy_service_layer:
    git:
      url: git@github.com:FyersDev/fy_service_layer.git
      ref: master

flutter: 
  uses-material-design: false
  assets:
    - assets/

###****** Snippet for enabling localization ******###
flutter_intl:
  enabled: false 
#   class_name: FyPackageName
#   main_locale: en 
#   arb_dir: lib/src/resource/constants/localization/intls 
#   output_dir: lib/src/resource/constants/localization 
#   use_deferred_loading: false
